# Generated by Django 4.2.3 on 2023-08-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Custom_User',
        ),
    ]
